temp commit

diff --git a/distribution/resources/bin/gateway b/distribution/resources/bin/gateway
--- a/distribution/resources/bin/gateway
+++ b/distribution/resources/bin/gateway
@@ -102,12 +102,6 @@ if [ -z "$JAVACMD" ] ; then
     fi
 fi
 
-JDK_18=`$JAVACMD -version 2>&1 | grep "1.8."`
-if [ "$JDK_18" = "" ]; then
-    echo "Error: Microgateway is supported only on Java 1.8"
-    exit 1
-fi
-
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
     JAVACMD=`cygpath --absolute --windows "$JAVACMD"`
@@ -116,6 +110,12 @@ fi
 if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA Package inside the microgateway runtime distribution is not working."
   exit 1
+fi
+
+JDK_18=`$JAVACMD -version 2>&1 | grep "1.8."`
+if [ "$JDK_18" = "" ]; then
+    echo "Error: Microgateway is supported only on Java 1.8"
+    exit 1
 fi
 
 # As we use different directory to keep microgateway configuration for the docker image
@@ -148,7 +148,7 @@ if [ -n "${BAL_JAVA_DEBUG+set}" ]; then
         exit 1
     else
       if [ -n "$JAVA_OPTS" ]; then
-        echo "Warn: User specified JAVA_OPTS may interfere with BAL_JAVA_DEBUG"
+        echo "Warning !!! User specified JAVA_OPTS may interfere with BAL_JAVA_DEBUG"
       fi
       # 'quiet=y' avoids breaking LSP protocol in debug mode
       JAVA_OPTS="$JAVA_OPTS -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=$BAL_JAVA_DEBUG,quiet=y"
